"""Contracts - Contract templates and analysis."""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, List

router = APIRouter()

# Common contract templates
CONTRACT_TEMPLATES = {
    "nda": "Non-Disclosure Agreement",
    "employment": "Employment Agreement",
    "lease": "Lease Agreement",
    "sale": "Sale Agreement",
    "service": "Service Agreement",
    "partnership": "Partnership Agreement",
    "consultancy": "Consultancy Agreement",
    "power_of_attorney": "Power of Attorney",
}

class ContractRequest(BaseModel):
    template_type: str
    parties: dict
    terms: Optional[List[str]] = None

@router.get("/contracts/templates")
async def list_contract_templates():
    """List available contract templates."""
    return {"templates": [{"id": k, "name": v} for k, v in CONTRACT_TEMPLATES.items()]}

@router.get("/contracts/template/{template_id}")
async def get_contract_template(template_id: str):
    """Get a specific contract template."""
    name = CONTRACT_TEMPLATES.get(template_id)
    if not name:
        raise HTTPException(status_code=404, detail="Template not found")
    
    return {
        "id": template_id,
        "name": name,
        "template": f"This is a template for {name}. Please consult a legal professional for a complete contract.",
    }

@router.post("/contracts/generate")
async def generate_contract(request: ContractRequest):
    """Generate a contract based on a template."""
    template_name = CONTRACT_TEMPLATES.get(request.template_type)
    if not template_name:
        raise HTTPException(status_code=404, detail="Template not found")
    
    # Generate a simple contract draft
    parties_str = ", ".join([f"{k}: {v}" for k, v in request.parties.items()])
    
    contract = f"""
{template_name}

Parties: {parties_str}

This agreement is made on [DATE] between the above-mentioned parties.

{chr(10).join(request.terms or [])}

Note: This is a draft generated by Pakistan Law App. Please consult a legal professional before using this contract.
"""
    
    return {
        "template_type": request.template_type,
        "contract": contract.strip(),
    }
