import React, { useState } from 'react';
import { Card } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Textarea } from '../components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select';
import { Checkbox } from '../components/ui/checkbox';
import { useToast } from '../components/ui/use-toast';
import { FileText, Download, Loader2 } from 'lucide-react';
import { Helmet } from 'react-helmet';
import { jsPDF } from 'jspdf';

const ExportBriefPage = () => {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    title: '',
    court: '',
    caseNumber: '',
    parties: {
      appellant: '',
      respondent: ''
    },
    facts: '',
    issues: '',
    arguments: '',
    relief: '',
    format: 'pdf'
  });

  const [sections, setSections] = useState({
    facts: true,
    issues: true,
    arguments: true,
    relief: true,
    citations: true
  });

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    if (name.includes('.')) {
      const [parent, child] = name.split('.');
      setFormData(prev => ({
        ...prev,
        [parent]: {
          ...prev[parent],
          [child]: value
        }
      }));
    } else {
      setFormData(prev => ({
        ...prev,
        [name]: value
      }));
    }
  };

  const handleExport = async () => {
    try {
      setLoading(true);

      switch (formData.format) {
        case 'pdf':
          await exportPDF();
          break;
        case 'doc':
          await exportDOC();
          break;
        case 'txt':
          await exportTXT();
          break;
        default:
          throw new Error('Unsupported format');
      }

      toast({
        title: "Export Complete",
        description: `Brief exported as ${formData.format.toUpperCase()}`
      });
    } catch (error) {
      toast({
        title: "Export Failed",
        description: error.message,
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const generateBriefContent = () => {
    const lines = [];
    
    lines.push('LEGAL BRIEF');
    lines.push('='.repeat(50));
    lines.push('');
    
    if (formData.title) {
      lines.push(`Title: ${formData.title}`);
      lines.push('');
    }
    
    if (formData.court) {
      lines.push(`Court: ${formData.court}`);
    }
    if (formData.caseNumber) {
      lines.push(`Case Number: ${formData.caseNumber}`);
    }
    lines.push('');
    
    lines.push('PARTIES');
    lines.push('-'.repeat(30));
    if (formData.parties.appellant) {
      lines.push(`Appellant: ${formData.parties.appellant}`);
    }
    if (formData.parties.respondent) {
      lines.push(`Respondent: ${formData.parties.respondent}`);
    }
    lines.push('');

    if (sections.facts && formData.facts) {
      lines.push('STATEMENT OF FACTS');
      lines.push('-'.repeat(30));
      lines.push(formData.facts);
      lines.push('');
    }

    if (sections.issues && formData.issues) {
      lines.push('ISSUES');
      lines.push('-'.repeat(30));
      lines.push(formData.issues);
      lines.push('');
    }

    if (sections.arguments && formData.arguments) {
      lines.push('ARGUMENTS');
      lines.push('-'.repeat(30));
      lines.push(formData.arguments);
      lines.push('');
    }

    if (sections.relief && formData.relief) {
      lines.push('PRAYER FOR RELIEF');
      lines.push('-'.repeat(30));
      lines.push(formData.relief);
      lines.push('');
    }

    lines.push(''.repeat(50));
    lines.push('Generated by Pakistan Law App');

    return lines.join('\n');
  };

  const exportPDF = async () => {
    const doc = new jsPDF();
    const content = generateBriefContent();
    const lines = doc.splitTextToSize(content, 180);
    
    let y = 20;
    lines.forEach(line => {
      if (y > 280) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 15, y);
      y += 5;
    });
    
    doc.save(`brief-${Date.now()}.pdf`);
  };

  const exportDOC = async () => {
    const content = generateBriefContent();
    const blob = new Blob([content], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `brief-${Date.now()}.doc`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportTXT = async () => {
    const content = generateBriefContent();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `brief-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <Helmet>
        <title>Export Brief | Pakistan Law App</title>
      </Helmet>

      <div className="min-h-screen bg-slate-50 py-8">
        <div className="max-w-4xl mx-auto px-4">
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-slate-900">Export Legal Brief</h1>
            <p className="text-slate-600 mt-2">Generate and export a professional legal brief</p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Form */}
            <div className="lg:col-span-2 space-y-6">
              <Card className="p-6">
                <h2 className="text-lg font-semibold mb-4">Case Information</h2>
                <div className="space-y-4">
                  <div>
                    <Label htmlFor="title">Brief Title</Label>
                    <Input
                      id="title"
                      name="title"
                      value={formData.title}
                      onChange={handleInputChange}
                      placeholder="Enter brief title"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="court">Court</Label>
                      <Input
                        id="court"
                        name="court"
                        value={formData.court}
                        onChange={handleInputChange}
                        placeholder="Court name"
                      />
                    </div>
                    <div>
                      <Label htmlFor="caseNumber">Case Number</Label>
                      <Input
                        id="caseNumber"
                        name="caseNumber"
                        value={formData.caseNumber}
                        onChange={handleInputChange}
                        placeholder="Case number"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="parties.appellant">Appellant</Label>
                      <Input
                        id="parties.appellant"
                        name="parties.appellant"
                        value={formData.parties.appellant}
                        onChange={handleInputChange}
                        placeholder="Appellant name"
                      />
                    </div>
                    <div>
                      <Label htmlFor="parties.respondent">Respondent</Label>
                      <Input
                        id="parties.respondent"
                        name="parties.respondent"
                        value={formData.parties.respondent}
                        onChange={handleInputChange}
                        placeholder="Respondent name"
                      />
                    </div>
                  </div>
                </div>
              </Card>

              <Card className="p-6">
                <h2 className="text-lg font-semibold mb-4">Brief Content</h2>
                <div className="space-y-4">
                  {sections.facts && (
                    <div>
                      <Label htmlFor="facts">Statement of Facts</Label>
                      <Textarea
                        id="facts"
                        name="facts"
                        value={formData.facts}
                        onChange={handleInputChange}
                        placeholder="Enter statement of facts..."
                        rows={4}
                      />
                    </div>
                  )}

                  {sections.issues && (
                    <div>
                      <Label htmlFor="issues">Issues</Label>
                      <Textarea
                        id="issues"
                        name="issues"
                        value={formData.issues}
                        onChange={handleInputChange}
                        placeholder="Enter legal issues..."
                        rows={4}
                      />
                    </div>
                  )}

                  {sections.arguments && (
                    <div>
                      <Label htmlFor="arguments">Arguments</Label>
                      <Textarea
                        id="arguments"
                        name="arguments"
                        value={formData.arguments}
                        onChange={handleInputChange}
                        placeholder="Enter legal arguments..."
                        rows={6}
                      />
                    </div>
                  )}

                  {sections.relief && (
                    <div>
                      <Label htmlFor="relief">Prayer for Relief</Label>
                      <Textarea
                        id="relief"
                        name="relief"
                        value={formData.relief}
                        onChange={handleInputChange}
                        placeholder="Enter prayer for relief..."
                        rows={4}
                      />
                    </div>
                  )}
                </div>
              </Card>
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
              <Card className="p-6">
                <h2 className="text-lg font-semibold mb-4">Sections</h2>
                <div className="space-y-3">
                  {Object.entries(sections).map(([key, checked]) => (
                    <div key={key} className="flex items-center space-x-2">
                      <Checkbox
                        id={key}
                        checked={checked}
                        onCheckedChange={(checked) =>
                          setSections(prev => ({ ...prev, [key]: checked }))
                        }
                      />
                      <Label htmlFor={key} className="capitalize">
                        {key}
                      </Label>
                    </div>
                  ))}
                </div>
              </Card>

              <Card className="p-6">
                <h2 className="text-lg font-semibold mb-4">Export Format</h2>
                <Select
                  value={formData.format}
                  onValueChange={(value) =>
                    setFormData(prev => ({ ...prev, format: value }))
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select format" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="pdf">PDF Document</SelectItem>
                    <SelectItem value="doc">Word Document</SelectItem>
                    <SelectItem value="txt">Text File</SelectItem>
                  </SelectContent>
                </Select>

                <Button
                  className="w-full mt-4"
                  onClick={handleExport}
                  disabled={loading}
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Exporting...
                    </>
                  ) : (
                    <>
                      <Download className="w-4 h-4 mr-2" />
                      Export Brief
                    </>
                  )}
                </Button>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ExportBriefPage;
